volumes:
  dados_mongo:

version: '2'
services:
  redis:
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo:4.4.1-bionic
    restart: always
    volumes:
      - dados_mongo:/data/db
      - ./docker/scripts/init.db.js:/docker-entrypoint-initdb.d/init.db.js
    environment:
      MONGO_INITDB_DATABASE: marvel
    ports:
      - 27017:27017
  app:
    image: openjdk:16-jdk-alpine3.12
    depends_on:
      - mongo
      - redis
